version: "3.8"

services: 
  server:
    build: 
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: laravelstarteri:latest
    container_name: laravelstarter
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    image: phputil:latest
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file: ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    image: composerutil:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    image: artisanutil:latest
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:14-alpine
    working_dir: /var/www/html
    container_name: npm
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html